### ISSUE TITLE
Clarification requested: am I expected to create a new Auth0 Application for every shiny app that I have?

### ISSUE THREAD

**Issue by daattali** [curso-r/auth0#17]
If I have 3 different shiny apps to authenticate, do I create 3 different Applications on the Auth0 website?

If the answer is yes, then a follow up question: Each Application has a unique Client ID and Secret, so maybe add some information about how to handle having multiple apps since the autho_key and secret env vars are being set as if there is only one combination that can exist

**Comment by jtrecenti** [comment]
Thank you, great issue.

You are not required to create two applications for two different shiny apps. Although, you do have to create two applications if you have different login settings, such as enable/disable google authentication, custom login page skin etc.

As you pointed out, the problem is that the documentation makes the user think that setting environment variables is the only way to use `auth0` package, and it would be really unpleasant to change the `.Renviron` file every time I start working on a new app.

I think that the best practice when you have multiple auth0 applications is to put the credentials directly in the `_auth0.yml` file, instead of using environment variables. I'll add more examples to address this problem.
