### ISSUE TITLE
When using separate server and ui files, unable to get session$userData

### ISSUE THREAD

**Issue by chadasmithphd** [curso-r/auth0#71]
My web app is using shiny dashboard package, even after wrapping server and ui functions, the session$user data was not accessible. After putting server and ui in app.R file, ran perfectly.

Really appreciate what you are doing and would be more than happy to contribute in some way. Thanks so much.

**Comment by jtrecenti** [comment]
Hi @chadasmithphd, thanks for the issue. Have you tried the solution using `global.R` file, documented here below? 

https://curso-r.github.io/auth0/articles/examples/ui-server-userinfo.html

Thanks!

**Comment by chadasmithphd** [comment]
Thanks for the response. I added an example here - sorry if this is not the best way to provide this:
git@github.com:chadasmithphd/testAuth0.git

**Comment by jtrecenti** [comment]
Nice. Your codes seem almost perfect. Two minor issues:

1. You don't have to `source()` the `global.R` file in `ui.R` or `server.R`
2. You have to make sure that you have a configured `_auth0.yml` file and that it's accessible
3. In order to run it using ui.R/server.R framework, it's important to use the `shiny::runApp()` function , after configuring the `options(shiny.port=8080)` for example (please do that outside the scripts) and `setwd()` to the directory where the files are included.

Sorry but I couldn't reproduce your issue yet.

See the prints below to my config and return

![Screenshot from 2020-05-09 20-12-46](https://user-images.githubusercontent.com/1425970/81487270-9dfedd80-9231-11ea-8441-c9a8f061bcb4.png)
![Screenshot from 2020-05-09 20-13-13](https://user-images.githubusercontent.com/1425970/81487272-9e977400-9231-11ea-8959-3862adcb7907.png)

**Comment by chadasmithphd** [comment]
Thanks so much for this assist. The issue was in fact that I had source() global R in both server and ui files. After deleting these lines, it works perfect!
